#!/usr/bin/env python3
"""Inner process (runs ON the LSF node, invoked by fabric_worker.py).

Assembles a per-leaf main.tcl + run.txt, invokes the mock `liberate`,
and exits 0 on success / non-zero on failure. The fabric_worker wrapper
reads the produced `.ldb` digest and writes it as data_version to the
status DB — this script no longer reports to Dagster (per the
non-blocking pull model; WHITEPAPER §3.5).
"""
import argparse
import subprocess
import sys
from pathlib import Path


def gen_main_tcl_leaf(root: str, pvt: str) -> str:
    return ("# main.tcl -- per-leaf (generated by the characterize asset)\n"
            f"source {root}/templates/template_{pvt}.tcl\n")


def gen_run_scr_leaf(root: str, pvt: str, cell: str, out_dir: str, main_path: str) -> str:
    L = ["# run.txt -- per-leaf liberate run (generated by the characterize asset)",
         f"# leaf: pvt={pvt} cell={cell}",
         f"source {root}/tool_env.csh",
         f"set_out_dir {out_dir}",
         f"read_main {main_path}",
         f"read_cell_list {root}/Mnpvt_cell_list.tcl",
         f"set_pvts {pvt}",
         f"set_cells {cell}",
         f"read_modelcard {pvt} {root}/modelcard/model_{pvt}.tcl",
         f"read_sections {pvt} {root}/sections/{pvt}",
         f"read_netlist {cell} {root}/netlist/{cell}.sp",
         "characterize_all"]
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sources-root", required=True)
    ap.add_argument("--work-dir", required=True)
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--pvt", required=True)
    ap.add_argument("--cell", required=True)
    ap.add_argument("--liberate", required=True)
    args = ap.parse_args()

    work = Path(args.work_dir)
    work.mkdir(parents=True, exist_ok=True)
    main_tcl = work / "main.tcl"
    run_scr = work / "run.txt"
    main_tcl.write_text(gen_main_tcl_leaf(args.sources_root, args.pvt))
    run_scr.write_text(
        gen_run_scr_leaf(args.sources_root, args.pvt, args.cell,
                         args.out_dir, str(main_tcl))
    )

    r = subprocess.run(
        [sys.executable, args.liberate, "-scr", str(run_scr)],
        capture_output=True, text=True,
    )
    sys.stdout.write(r.stdout)
    sys.stderr.write(r.stderr)
    return r.returncode


if __name__ == "__main__":
    sys.exit(main())
