#!/usr/bin/env python3
"""Pipes-aware inner process (run on the compute node by the mock bsub).

Self-contained (stdlib + dagster_pipes): assembles a per-leaf main.tcl +
run.scr, invokes the mock `liberate`, parses the .ldb digest, and reports
it as the asset's data_version via Pipes. Vendored + inlined from
converted/core/liberate_inner.py so it can run by path with no package
imports.
"""
import argparse
import subprocess
import sys
from pathlib import Path

from dagster_pipes import open_dagster_pipes


def gen_main_tcl_leaf(root: str, pvt: str) -> str:
    return ("# main.tcl -- per-leaf (generated by the characterize asset)\n"
            f"source {root}/templates/template_{pvt}.tcl\n")


def gen_run_scr_leaf(root: str, pvt: str, cell: str, out_dir: str, main_path: str) -> str:
    L = ["# run.scr -- per-leaf liberate run (generated by the characterize asset)",
         f"# leaf: pvt={pvt} cell={cell}",
         f"source {root}/tool_env.csh",
         f"set_out_dir {out_dir}",
         f"read_main {main_path}",
         f"read_cell_list {root}/Mnpvt_cell_list.tcl",
         f"set_pvts {pvt}",
         f"set_cells {cell}",
         f"read_modelcard {pvt} {root}/modelcard/model_{pvt}.tcl",
         f"read_sections {pvt} {root}/sections/{pvt}",
         f"read_netlist {cell} {root}/netlist/{cell}.sp",
         "characterize_all"]
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sources-root", required=True)
    ap.add_argument("--work-dir", required=True)
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--pvt", required=True)
    ap.add_argument("--cell", required=True)
    ap.add_argument("--liberate", required=True)
    args = ap.parse_args()

    with open_dagster_pipes() as pipes:
        work = Path(args.work_dir)
        work.mkdir(parents=True, exist_ok=True)
        main_tcl = work / "main.tcl"
        run_scr = work / "run.scr"
        main_tcl.write_text(gen_main_tcl_leaf(args.sources_root, args.pvt))
        run_scr.write_text(
            gen_run_scr_leaf(args.sources_root, args.pvt, args.cell,
                             args.out_dir, str(main_tcl))
        )

        pipes.log.info(f"liberate_inner: characterizing {args.pvt}/{args.cell}")
        r = subprocess.run(
            [sys.executable, args.liberate, "-scr", str(run_scr)],
            capture_output=True, text=True,
        )
        if r.returncode != 0:
            pipes.log.error(f"liberate failed: {r.stderr.strip()}")
            return r.returncode

        ldb = Path(args.out_dir) / f"{args.pvt}__{args.cell}.ldb"
        digest = "unknown"
        for line in ldb.read_text().splitlines():
            if line.startswith("digest "):
                digest = line.split()[1]
        pipes.report_asset_materialization(
            data_version=digest,
            metadata={"pvt": args.pvt, "cell": args.cell, "ldb": str(ldb)},
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
