"""The L0 generators: produce each source artifact from `config/liberate.yaml`
instead of keeping N hardcoded, duplicated files. These reproduce the
flow-src/ files byte-for-byte (path-free files exactly; main.tcl / run.scr
identically given the same root) — see tests/test_generator_equivalence.py.

DO extract sources to template + config. DON'T copy flow-src files in, and
DON'T read $FLOW_SRC paths at runtime.
"""
from pathlib import Path

from core.render import render

# --- path-free templates (reproduce flow-src param files exactly) ---------

TEMPLATE_TCL = (
    "# template tcl for pvt $pvt\n"
    "set_var process $process\n"
    "set_var voltage $voltage\n"
    "set_var temperature $temperature\n"
    "set_var library_name lib__$pvt\n"
)
SECTION_TCL = (
    "# section $n for pvt $pvt\n"
    "define_section $n\n"
    "set_section_param $n mode char\n"
    "set_section_param $n pvt $pvt\n"
    "set_section_param $n index ${n}0\n"
)
MODEL_TCL = (
    "# model card for pvt $pvt\n"
    "load_model ${process}_models.lib\n"
    "set_corner $pvt\n"
    "set_temp $temperature\n"
)
NETLIST_SP = (
    "* netlist for cell $cell\n"
    ".subckt $cell $pins\n"
    "* device stubs for $cell\n"
    ".ends $cell\n"
)


def gen_template(cfg, pvt: str) -> str:
    p = cfg.pvts[pvt]
    return render(TEMPLATE_TCL, pvt=pvt, process=p["process"],
                  voltage=p["voltage"], temperature=p["temperature"])


def gen_section(cfg, pvt: str, n: int) -> str:
    return render(SECTION_TCL, n=n, pvt=pvt)


def gen_model_card(cfg, pvt: str) -> str:
    p = cfg.pvts[pvt]
    return render(MODEL_TCL, pvt=pvt, process=p["process"], temperature=p["temperature"])


def gen_netlist(cfg, cell: str) -> str:
    return render(NETLIST_SP, cell=cell, pins=cfg.cells[cell]["pins"])


def gen_cell_list(cfg) -> str:
    lines = ["# Mnpvt cell list (single file; by cell)",
             "set_cell \\( " + " ".join(cfg.cell_keys) + " \\)"]
    for c in cfg.cell_keys:
        lines.append(f"set_cell_pins {c} {{ {cfg.cells[c]['pins']} }}")
    return "\n".join(lines) + "\n"


# --- path-bearing orchestration (only the embedded root changes) ----------

def gen_main_tcl(cfg, root: str) -> str:
    lines = ["# main.tcl -- aggregates the per-pvt template tcls (HARDCODED paths)"]
    for pvt in cfg.pvt_keys:
        lines.append(f"source {root}/templates/template_{pvt}.tcl")
    return "\n".join(lines) + "\n"


def gen_run_scr_full(cfg, root: str) -> str:
    L = ["# run.scr -- complete liberate run script (HARDCODED paths)",
         "# This is the single script the original flow feeds to `liberate`.",
         f"source {root}/tool_env.csh",
         f"set_out_dir {root}/out",
         f"read_main {root}/main.tcl",
         f"read_cell_list {root}/Mnpvt_cell_list.tcl",
         "set_pvts " + " ".join(cfg.pvt_keys),
         "set_cells " + " ".join(cfg.cell_keys)]
    for pvt in cfg.pvt_keys:
        L.append(f"read_modelcard {pvt} {root}/modelcard/model_{pvt}.tcl")
    for pvt in cfg.pvt_keys:
        L.append(f"read_sections {pvt} {root}/sections/{pvt}")
    for cell in cfg.cell_keys:
        L.append(f"read_netlist {cell} {root}/netlist/{cell}.sp")
    L.append("characterize_all")
    return "\n".join(L) + "\n"


# --- per-leaf orchestration (used by the Dagster `characterize` asset) ----

def gen_main_tcl_leaf(root: str, pvt: str) -> str:
    return ("# main.tcl -- per-leaf (generated by the Dagster characterize asset)\n"
            f"source {root}/templates/template_{pvt}.tcl\n")


def gen_run_scr_leaf(root: str, pvt: str, cell: str, out_dir: str, main_path: str) -> str:
    L = ["# run.scr -- per-leaf liberate run (generated by the Dagster characterize asset)",
         f"# leaf: pvt={pvt} cell={cell}",
         f"source {root}/tool_env.csh",
         f"set_out_dir {out_dir}",
         f"read_main {main_path}",
         f"read_cell_list {root}/Mnpvt_cell_list.tcl",
         f"set_pvts {pvt}",
         f"set_cells {cell}",
         f"read_modelcard {pvt} {root}/modelcard/model_{pvt}.tcl",
         f"read_sections {pvt} {root}/sections/{pvt}",
         f"read_netlist {cell} {root}/netlist/{cell}.sp",
         "characterize_all"]
    return "\n".join(L) + "\n"


def write_sources(cfg, dest_dir, path_root=None) -> None:
    """Reproduce the full flow-src tree under dest_dir. Embedded paths use
    path_root (defaults to dest_dir). Used by the generator assets and to
    prove generation reproduces flow-src."""
    d = Path(dest_dir)
    path_root = path_root if path_root is not None else str(d)
    for sub in ("templates", "modelcard", "netlist"):
        (d / sub).mkdir(parents=True, exist_ok=True)
    for pvt in cfg.pvt_keys:
        (d / "templates" / f"template_{pvt}.tcl").write_text(gen_template(cfg, pvt))
        (d / "modelcard" / f"model_{pvt}.tcl").write_text(gen_model_card(cfg, pvt))
        sdir = d / "sections" / pvt
        sdir.mkdir(parents=True, exist_ok=True)
        for n in cfg.sections:
            (sdir / f"section{n}.tcl").write_text(gen_section(cfg, pvt, n))
    for cell in cfg.cell_keys:
        (d / "netlist" / f"{cell}.sp").write_text(gen_netlist(cfg, cell))
    (d / "Mnpvt_cell_list.tcl").write_text(gen_cell_list(cfg))
    (d / "main.tcl").write_text(gen_main_tcl(cfg, path_root))
    (d / "run.scr").write_text(gen_run_scr_full(cfg, path_root))
